ASP.NET Core/WebAppDemoRazorPages/Controllers/OrganizationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using DemoClients;
using WebAppDemoRazorPages.Data;

namespace WebAppDemoRazorPages.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class OrganizationsController : ControllerBase
    {
        private readonly ApplicationDbContext _context;

        public OrganizationsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: api/Organizations
        [HttpGet]
        public async Task<ActionResult<IEnumerable<Organization>>> GetOrganizations()
        {
          if (_context.Organizations == null)
          {
              return NotFound();
          }
            return await _context.Organizations.ToListAsync();
        }

        // GET: api/Organizations/5
        [HttpGet("{id}")]
        public async Task<ActionResult<Organization>> GetOrganization(int id)
        {
          if (_context.Organizations == null)
          {
              return NotFound();
          }
            var organization = await _context.Organizations.FindAsync(id);

            if (organization == null)
            {
                return NotFound();
            }

            return organization;
        }

        // PUT: api/Organizations/5
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPut("{id}")]
        public async Task<IActionResult> PutOrganization(int id, Organization organization)
        {
            if (id != organization.Id)
            {
                return BadRequest();
            }

            _context.Entry(organization).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!OrganizationExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/Organizations
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPost]
        public async Task<ActionResult<Organization>> PostOrganization(Organization organization)
        {
          if (_context.Organizations == null)
          {
              return Problem("Entity set 'ApplicationDbContext.Organizations'  is null.");
          }
            _context.Organizations.Add(organization);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetOrganization", new { id = organization.Id }, organization);
        }

        // DELETE: api/Organizations/5
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteOrganization(int id)
        {
            if (_context.Organizations == null)
            {
                return NotFound();
            }
            var organization = await _context.Organizations.FindAsync(id);
            if (organization == null)
            {
                return NotFound();
            }

            _context.Organizations.Remove(organization);
            await _context.SaveChangesAsync();

            return NoContent();
        }

        private bool OrganizationExists(int id)
        {
            return (_context.Organizations?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

ASP.NET Core/WebAppDemoRazorPages/Pages/Organizations/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using DemoClients;
using WebAppDemoRazorPages.Data;
using Microsoft.AspNetCore.Authorization;

namespace WebAppDemoRazorPages.Pages.Organizations
{
    [Authorize]
    public class CreateModel : PageModel
    {
        private readonly WebAppDemoRazorPages.Data.ApplicationDbContext _context;

        public CreateModel(WebAppDemoRazorPages.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Organization Organization { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid || _context.Organizations == null || Organization == null)
            {
                return Page();
            }

            _context.Organizations.Add(Organization);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

ASP.NET Core/WebAppDemoRazorPages/Pages/Organizations/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DemoClients;
using WebAppDemoRazorPages.Data;
using Microsoft.AspNetCore.Authorization;

namespace WebAppDemoRazorPages.Pages.Organizations
{
    [Authorize]
    public class DeleteModel : PageModel
    {
        private readonly WebAppDemoRazorPages.Data.ApplicationDbContext _context;

        public DeleteModel(WebAppDemoRazorPages.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
      public Organization Organization { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Organizations == null)
            {
                return NotFound();
            }

            var organization = await _context.Organizations.FirstOrDefaultAsync(m => m.Id == id);

            if (organization == null)
            {
                return NotFound();
            }
            else 
            {
                Organization = organization;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.Organizations == null)
            {
                return NotFound();
            }
            var organization = await _context.Organizations.FindAsync(id);

            if (organization != null)
            {
                Organization = organization;
                _context.Organizations.Remove(Organization);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

ASP.NET Core/WebAppDemoRazorPages/Pages/Organizations/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DemoClients;
using WebAppDemoRazorPages.Data;
using Microsoft.AspNetCore.Authorization;

namespace WebAppDemoRazorPages.Pages.Organizations
{
    [Authorize]
    public class DetailsModel : PageModel
    {
        private readonly WebAppDemoRazorPages.Data.ApplicationDbContext _context;

        public DetailsModel(WebAppDemoRazorPages.Data.ApplicationDbContext context)
        {
            _context = context;
        }

      public Organization Organization { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Organizations == null)
            {
                return NotFound();
            }

            var organization = await _context.Organizations.FirstOrDefaultAsync(m => m.Id == id);
            if (organization == null)
            {
                return NotFound();
            }
            else 
            {
                Organization = organization;
            }
            return Page();
        }
    }
}

ASP.NET Core/WebAppDemoRazorPages/Pages/Organizations/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DemoClients;
using WebAppDemoRazorPages.Data;
using Microsoft.AspNetCore.Authorization;

namespace WebAppDemoRazorPages.Pages.Organizations
{
    [Authorize]
    public class EditModel : PageModel
    {
        private readonly WebAppDemoRazorPages.Data.ApplicationDbContext _context;

        public EditModel(WebAppDemoRazorPages.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Organization Organization { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Organizations == null)
            {
                return NotFound();
            }

            var organization =  await _context.Organizations.FirstOrDefaultAsync(m => m.Id == id);
            if (organization == null)
            {
                return NotFound();
            }
            Organization = organization;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Organization).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!OrganizationExists(Organization.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool OrganizationExists(int id)
        {
          return (_context.Organizations?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

ASP.NET Core/WebAppDemoRazorPages/Pages/Organizations/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DemoClients;
using WebAppDemoRazorPages.Data;
using System.Linq.Expressions;
using System.Xml;
using Microsoft.EntityFrameworkCore.Query.SqlExpressions;
using WebAppDemoRazorPages.Models;
using Bogus;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Components;
// route [namespace:Organizations]/[PageModel:Index]
namespace WebAppDemoRazorPages.Pages.Organizations
{
    [Authorize(Roles = "Administrator")]
    public class IndexModel : PageModel,IPaginated,IFirterable
    {


        private readonly WebAppDemoRazorPages.Data.ApplicationDbContext _context;

        public IndexModel(WebAppDemoRazorPages.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IList<Organization> Organization { get;set; } = default!;
        [BindProperty(SupportsGet = true)]
        public string Filter { get; set; }

        public int PageSize { get; set; } = 20;
        [BindProperty(SupportsGet =true)]
        public int Skip { get; set; } = 0;

        public int CountItems { get; set; }
 
        async Task GetItems(IQueryable<Organization> query)
        {
            var containsMethod = typeof(string).GetMethod("Contains", new Type[] { typeof(string) });
            if (containsMethod == null) return;

            var AvaliableFields = typeof(Organization).GetProperties().Where(p => p.PropertyType == typeof(string)).Select(s => s.Name).ToArray();


            // Define the expression parameters
            ParameterExpression parameter = Expression.Parameter(typeof(Organization), "entity");



            if (Filter != null)
            {
                Expression? predicate = null;
                foreach (var field in AvaliableFields)
                {

                    if (predicate == null)
                    {
                        predicate = Expression.Call(Expression.Property(parameter, field), containsMethod, Expression.Constant(Filter));
                    }
                    else
                    {
                        predicate = Expression.OrElse(predicate, Expression.Call(Expression.Property(parameter, field), containsMethod, Expression.Constant(Filter)));
                    }
                }

                // Create the lambda expression
                Expression<Func<Organization, bool>> lambda = Expression.Lambda<Func<Organization, bool>>(predicate, parameter);
                query = query.Where(lambda);
            }

            CountItems = await query.CountAsync();
            Organization = await query.OrderBy(o=>o.Id).Skip(Skip).Take(PageSize).ToListAsync();
        }


        public async Task OnGetAsync()
        {
            
            if (_context.Organizations != null)
            {
                await GetItems(_context.Organizations.AsQueryable());
            }
        }
 
        public async Task OnPostFilterAsync()
        {
            if (_context.Organizations != null)
            {
                var query = _context.Organizations.AsQueryable(); 
                // get string type property names
                await GetItems(query);

            }
        }

        public async Task OnPostDeleteAsync(int? id)
        {

            if (id == null || _context.Organizations == null)
            {
                return ;
            }
            var organization = await _context.Organizations.FindAsync(id);

            if (organization != null)
            {
                
                _context.Organizations.Remove(organization);
                await _context.SaveChangesAsync();
            }
            await GetItems(_context.Organizations.AsQueryable()); 
        }

        public async Task OnPostRandomGenerateAsync()
        {
            
            if (_context.Organizations == null)
            {
                return;
            }

            for (int i = 0; i < 1; i++)
            {
                var organization = new Faker<Organization>()
                    .Rules((f,o) =>
                    {
                        o.Name = f.Company.CompanyName();
                        o.FullName = $"{o.Name} {f.Company.CompanySuffix()}";
                        o.Created = f.Date.Between(new DateTime(1900, 1, 1), new DateTime(2023, 12, 31));
                    }).Generate(100000);
                await _context.AddRangeAsync(organization);
                await _context.SaveChangesAsync();
            }
            
            await GetItems(_context.Organizations.AsQueryable());
        }

    }
}

ASP.NET Core/WebAppDemoRazorPages/Pages/Organizations/Create.cshtml
@page
@model WebAppDemoRazorPages.Pages.Organizations.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Organization</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Organization.Name" class="control-label"></label>
                <input asp-for="Organization.Name" class="form-control" />
                <span asp-validation-for="Organization.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Organization.FullName" class="control-label"></label>
                <input asp-for="Organization.FullName" class="form-control" />
                <span asp-validation-for="Organization.FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Organization.Created" class="control-label"></label>
                <input asp-for="Organization.Created" class="form-control" />
                <span asp-validation-for="Organization.Created" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ASP.NET Core/WebAppDemoRazorPages/Pages/Organizations/Delete.cshtml
@page
@model WebAppDemoRazorPages.Pages.Organizations.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Organization</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Organization.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Organization.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Organization.FullName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Organization.FullName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Organization.Created)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Organization.Created)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Organization.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

ASP.NET Core/WebAppDemoRazorPages/Pages/Organizations/Details.cshtml
@page
@model WebAppDemoRazorPages.Pages.Organizations.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Organization</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Organization.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Organization.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Organization.FullName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Organization.FullName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Organization.Created)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Organization.Created)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.Organization?.Id">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

ASP.NET Core/WebAppDemoRazorPages/Pages/Organizations/Edit.cshtml
@page
@model WebAppDemoRazorPages.Pages.Organizations.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Organization</h4>
<hr />
<div class="row">
    <div class="col-md-8">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Organization.Id" />
            <div class="form-group">
                <div class="row">
                    <div class="col-md-2">
                        <label asp-for="Organization.Name" class="control-label"></label>
                    </div>
                    <div class="col-md-10 d-grid">
                        <input asp-for="Organization.Name" class="form-contro" />
                    </div>
                </div>
                <span asp-validation-for="Organization.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Organization.FullName" class="control-label"></label>
                <input asp-for="Organization.FullName" class="form-control" />
                <span asp-validation-for="Organization.FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Organization.Created" class="control-label"></label>
                <input asp-for="Organization.Created" class="form-control" />
                <span asp-validation-for="Organization.Created" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ASP.NET Core/WebAppDemoRazorPages/Pages/Organizations/Index.cshtml
@page
@model WebAppDemoRazorPages.Pages.Organizations.IndexModel
@using DemoClients
@using Microsoft.AspNetCore.Mvc.Localization;
@inject IViewLocalizer Localizer

@{
    ViewData["Title"] = Localizer["Index"];
    var sl = Html.GetEnumSelectList<DirectionSearch>();
    
}

<h1>@Localizer["Організації"]</h1>
<form asp-page-handler="RandomGenerate">
    <div class="row text-center">
        <div class="col-12 col-md-3">
            <input type="submit" value=@Localizer["Генерувати"] class="btn btn-outline-primary w-100 mt-2 mt-md-0" />
        </div>
    </div>
</form>
<div class="row">
    <div class="col-12 col-md-4">
        <a asp-page="Create" class="btn btn-outline-primary d-md-inline-block d-flex justify-content-center" >Додати</a>
    </div>
    <div class="col-12 col-md-8">

        <form asp-page-handler="filter">
            <div class="row text-center">
                <div class="col-12 col-md-4 d-flex align-items-center">
                    @Localizer["Full text search:"]
                </div>
                <div class="col-12 col-md-5 d-grid">
                    <input type="text" asp-for="Filter" />
                 </div>
                <div class="col-12 col-md-3">
                    <input type="submit" value=@Localizer["Застосувати"] class="btn btn-outline-primary w-100 mt-2 mt-md-0" />
                </div>
            </div>
        </form>
       
    </div>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Organization[0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Organization[0].FullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Organization[0].Created)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Organization) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Created)
            </td>
            <td>
                <a asp-page="./Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-page="./Details" asp-route-id="@item.Id">Details</a>
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal@(item.Id)">
                        Delete
                    </button>
                    <!-- Modal -->
                    <div class="modal fade" id="exampleModal@(item.Id)" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Організації видалення</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    Буде видалено оганізацію @Html.DisplayFor(modelItem => item.Name)
                                
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                    <form method="post" asp-page-handler="Delete" asp-route-id="@item.Id">
                                        <input type="hidden" asp-for="@item.Id" />
                                        <input type="submit" value="Delete" class="btn btn-danger" /> |
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
        </tr>
}
    </tbody>
</table>

@await Html.PartialAsync("_paginator",Model)