ASP.NET Core/WebAppDemoRazorPages/Controllers/ToolsController.cs
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;

namespace WebAppDemoRazorPages.Controllers
{
    public class ToolsController : Controller
    {
        
        [Route("/")]
        [HttpPost]
        public IActionResult SetLanguage(string culture,string returnUrl) // 20200301
        {
            Response.Cookies.Append(CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1)});
            return LocalRedirect(returnUrl);
        }
    }
}

ASP.NET Core/WebAppDemoRazorPages/Pages/Shared/_SelectLanguagePartial.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebAppDemoRazorPages.Pages.Shared
{
    public class _SelectLanguagePartialModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ASP.NET Core/WebAppDemoRazorPages/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebAppDemoRazorPages</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebAppDemoRazorPages.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">WebAppDemoRazorPages</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Organizations/Index">Organizations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/ajaxDemo">AjaxDemo</a>
                        </li>

                    </ul>
                    <partial name="_SelectLanguagePartial"/>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebAppDemoRazorPages - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ASP.NET Core/WebAppDemoRazorPages/Pages/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Localization;
@using Microsoft.Extensions.Options;
@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
    var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}";
}
<div title="@Localizer["Request culture provider:"] @requestCulture?.Provider?.GetType().Name">
    <form id="selectLanguage" asp-controller="Tools"
          asp-action="SetLanguage" asp-route-returnUrl="@returnUrl"
          method="post" class="form-horizontal" role="form">
        <label asp-for="@requestCulture.RequestCulture.UICulture.Name">@Localizer["Language:"]</label> <select name="culture"
                                                                                                               onchange="this.form.submit();"
                                                                                                               asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems">
        </select>
    </form>
</div>

ASP.NET Core/WebAppDemoRazorPages/Pages/Shared/_paginator.cshtml
@model object
@using Models
@{
    IPaginated paginated = Model as IPaginated;
    IFirterable firterable = Model as IFirterable;
    if (paginated == null)
    {
        <div class="alert alert-danger align-self-center" role="alert">
            Do not implentation Interface IPaginated for PageModel;
        </div>
    }
    else
    {
         int pages = paginated.CountItems / paginated.PageSize + (paginated.CountItems % paginated.PageSize > 0 ? 1 : 0);
         if (pages > 1)
         {
            int curentPage = paginated.Skip == 0 ? 1 : paginated.Skip / paginated.PageSize + 1;
            string previosState = paginated.Skip == 0 ? "disabled" : "";
            // show only five tabs
            <nav aria-label="..." >
                <ul class="pagination justify-content-center">
                @{
                    if (curentPage == 1)
                {
                    <li class="page-item disabled">
                        <span class="page-link">First</span>
                    </li>
                }
                else
                {
                    <li class="page-item">
                        <a class="page-link" asp-page="" asp-route-skip="0" asp-route-filter="@firterable?.Filter">First</a>
                            </li>
                        }

                        int start=0;
                        if (pages > 9)
                        {
                            if (curentPage>5)
                            {
                                if (curentPage > pages - 5)
                                    start = pages - 9;
                                else
                                    start = curentPage-5;
                            }
                        }


                        for (int i = 1; i < 10; i++)
                        {
                            int pageNumber = i + start;
                            if (curentPage == pageNumber)
                            {
                                <li class="page-item active" aria-current="page">
                                    <span class="page-link">@pageNumber</span>
                                </li>
                            }
                            else
                            {
                                <li class="page-item"><a class="page-link" asp-page="" asp-route-skip="@((pageNumber-1)*paginated.PageSize)" asp-route-filter="@firterable.Filter">@pageNumber</a></li>
                            }
                }

                if (curentPage == pages)
                {
                    <li class="page-item disable">
                        <span class="page-link">Last</span>
                    </li>
                }
                else
                {
                    <li class="page-item">
                        <a class="page-link" asp-page="" asp-route-skip="@((pages-1)*paginated.PageSize)" asp-route-filter="@firterable?.Filter">Last @pages</a>
                    </li>
                }
                }
                </ul>
            </nav>
        }
    
    }
}